export const FETCH_ITEMS_BEGIN = "FETCH_ITEMS_BEGIN";
export type FETCH_ITEMS_BEGIN = typeof FETCH_ITEMS_BEGIN;

export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export type FETCH_ITEMS_SUCCESS = typeof FETCH_ITEMS_SUCCESS;

export const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";
export type FETCH_ITEMS_FAILURE = typeof FETCH_ITEMS_FAILURE;
